name: graduation_project
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.3
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1


# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/images/logo/1024.png"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/appstore.png"
  min_sdk_android: 21


flutter:

  uses-material-design: true
  assets:
    - assets\images\logo\appstore.png
   # - assets\images\onBoarding\

