name: graduation_project
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  fl_chart:  ^0.66.0 
  smooth_page_indicator: ^1.1.0
  lottie: ^2.6.0
  http: ^1.3.0
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.3
  shared_preferences: ^2.3.3
  provider: ^6.1.2
  intl: ^0.20.2
  image_picker: ^1.0.7
  jwt_decoder: ^2.0.1
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3


# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/images/logo/1024.png"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/shop.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/images/logo/shop.png"
  adaptive_icon_background: "#FFFFFF" 


flutter:

  uses-material-design: true
  assets:
    - assets\images\logo\appstore.png
    - assets\images\profileDefultImage\defultImage.png
    - assets\animation\firstImage.json
    - assets\animation\thirdImage.json
    - assets\animation\secondImage.json
    - assets\images\logo\bag.png
    - assets/images/logo/bag (1).png
    - assets/images/logo/shop.png
    - assets\images\logo\shop.png
    - assets/images/logo/shop_512x512.png
    - assets\images\logo\shop_512x512.png

